version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db-volume/conf.d:/etc/mysql/conf.d
      - ./db-volume/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rbgksla
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
